### ISSUE TITLE
管理されないstateのワーニングが出ているので修正する

### ISSUE THREAD

**Issue by kamataryo** [geolonia/app.geolonia.com#334]
```
index.js:1 Warning: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.
    at input
    at div
    at Paper (http://localhost:3000/static/js/vendors~main.chunk.js:25091:23)
    at WithStyles (http://localhost:3000/static/js/vendors~main.chunk.js:45468:31)
    at div
    at Grid (http://localhost:3000/static/js/vendors~main.chunk.js:17046:35)
    at WithStyles (http://localhost:3000/static/js/vendors~main.chunk.js:45468:31)
    at div
    at Grid (http://localhost:3000/static/js/vendors~main.chunk.js:17046:35)
    at WithStyles (http://localhost:3000/static/js/vendors~main.chunk.js:45468:31)
    at GeoJSONMeta (http://localhost:3000/static/js/main.chunk.js:5300:5)
    at ConnectFunction (http://localhost:3000/static/js/vendors~main.chunk.js:130381:75)
    at div
    at div
    at Content (http://localhost:3000/static/js/main.chunk.js:3961:66)
    at ConnectFunction (http://localhost:3000/static/js/vendors~main.chunk.js:130381:75)
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:133274:29)
    at Router (http://localhost:3000/static/js/vendors~main.chunk.js:132909:30)
    at HashRouter (http://localhost:3000/static/js/vendors~main.chunk.js:132574:35)
    at Router
    at WithStyles (http://localhost:3000/static/js/vendors~main.chunk.js:45468:31)
    at main
    at div
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:133274:29)
    at Switch (http://localhost:3000/static/js/vendors~main.chunk.js:133476:29)
    at Router (http://localhost:3000/static/js/vendors~main.chunk.js:132909:30)
    at HashRouter (http://localhost:3000/static/js/vendors~main.chunk.js:132574:35)
    at div
    at ThemeProvider (http://localhost:3000/static/js/vendors~main.chunk.js:44170:24)
    at Paperbase (http://localhost:3000/static/js/main.chunk.js:10863:5)
    at ConnectFunction (http://localhost:3000/static/js/vendors~main.chunk.js:130381:75)
    at WithStyles (http://localhost:3000/static/js/vendors~main.chunk.js:45468:31)
    at AuthContainer (http://localhost:3000/static/js/main.chunk.js:2649:5)
    at ConnectFunction (http://localhost:3000/static/js/vendors~main.chunk.js:130381:75)
    at Provider (http://localhost:3000/static/js/vendors~main.chunk.js:130094:20)
    at App
    ```

**Comment by kamataryo** [comment]
draft -> public に切り替えたときに発生するみたい。
