### ISSUE TITLE
サブページのクライアントサイドルーティング

### ISSUE THREAD

**Issue by kamataryo** [geolonia/app.geolonia.com#601]
`/#/api-keys/${key_id}` でリロードすると `/#/api-keys` に遷移する。

**Comment by kamataryo** [comment]
位置情報サービスも同様。#608 の後に対応

**Comment by kamataryo** [comment]
メモ: 遷移したときに以下のワーニングが発生する。このIssue の対応で解消できると思うので、一緒に確認。

```
index.js:1 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at MapEditorElement (http://localhost:3000/static/js/main.chunk.js:5481:5)
    at div
    at GeoJson (http://localhost:3000/static/js/main.chunk.js:2720:82)
```
